# fleet.yaml
targetCustomizations:
  - name: production
    clusterSelector:
      matchLabels:
        sigaint.au/environment: production
    kustomize:
      dir: overlays/production

  - name: development
    clusterSelector:
      matchLabels:
        sigaint.au/environment: development
    kustomize:
      dir: overlays/development


dependsOn:
  - selector:
      matchLabels:
        component: velero-install
  - selector:
      matchLabels:
        component: external-secrets-operator-install