apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matomo-db-credentials
  namespace: customer-sites
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: matomo-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: mariadb-root-password
      remoteRef:
        key: MATOMO_DB_ROOT_PASSWORD
