# fleet.yaml
defaultNamespace: velero
labels:
  component: velero-install
helm:
  repo: https://vmware-tanzu.github.io/helm-charts
  name: velero
  releaseName: velero
  valuesFiles:
    - values/production.yaml
