# fleet.yaml
defaultNamespace: velero
labels:
  component: velero-install
helm:
  repo: oci://dp.apps.rancher.io/charts
  chart: velero
  version: 12.0.0
  releaseName: velero
  valuesFiles:
    - values/production.yaml
