# fleet.yaml
targetCustomizations:
  - name: production
    clusterSelector:
      matchLabels:
        sigaint.au/environment: production
    kustomize:
      dir: overlays/production

dependsOn:
  - selector:
      matchLabels:
        component: cert-manager-operator-install
  - selector:
      matchLabels:
        component: external-secrets-operato-install