vminsert:
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi

vmselect:
  replicaCount: 2

vmstorage:
  replicaCount: 3
  persistentVolume:
    enabled: true
    size: 100Gi
    storageClass: "longhorn"
  retentionPeriod: "30d"

vmauth:
  enabled: true