apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: GRAFANA_ZITADEL_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: GRAFANA_ZITADEL_CLIENT_SECRET
