# fleet.yaml
defaultNamespace: metallb-system
labels:
  component: metallb-operator-install

# Deploy MetalLB Helm chart only on the k3s-lhm clusters.
# Do NOT deploy on syd-rancher-prod (Sydney), which uses hostNetwork Traefik.

targetRestrictions:
  - clusterSelector:
      matchExpressions:
        - key:  sigaint.au/cluster-id
          operator: NotIn
          values:
            - rancher-syd-prod

targetCustomizations:
  - name: k3s-lhm-prod
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: k3s-lhm-prod
    helm:
      repo: https://metallb.github.io/metallb
      chart: metallb
      version: 0.16.1
      releaseName: metallb
      valuesFiles:
        - values/production.yaml
      takeOwnership: true

  - name: k3s-lhm-devel
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: k3s-lhm-devel
    helm:
      repo: https://metallb.github.io/metallb
      chart: metallb
      version: 0.16.1
      releaseName: metallb
      valuesFiles:
        - values/production.yaml
      takeOwnership: true

diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: metallb-webhook-configuration
      operations:
        - op: remove
          path: /webhooks
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: metallb-webhook-configuration
      operations:
        - op: remove
          path: /webhooks