# fleet.yaml
defaultNamespace: traefik
labels:
  component: traefik-install
helm:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 39.0.6
  releaseName: traefik
  valuesFiles:
    - values/production.yaml
