# fleet.yaml
defaultNamespace: traefik
labels:
  component: traefik-install
helm:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: 39.0.6
  releaseName: traefik

targetCustomizations:
  - name: k3s-lhm-prod
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: k3s-lhm-prod
    helm:
      valuesFiles:
        - values/k3s-lhm-prod.yaml
    dependsOn:
      - selector:
          matchLabels:
            component: metallb-operator-install

  - name: k3s-lhm-devel
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: k3s-lhm-devel
    helm:
      valuesFiles:
        - values/k3s-lhm-devel.yaml
    dependsOn:
      - selector:
          matchLabels:
            component: metallb-operator-install

  - name: rancher-syd-prod
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: rancher-syd-prod
    helm:
      valuesFiles:
        - values/rancher-syd-prod.yaml
