# Supporting NetworkPolicies for Falcosidekick (k3s-lhm-* only).
defaultNamespace: falco
labels:
  component: falcosidekick-config

targetCustomizations:
  - name: k3s-lhm-clusters
    clusterSelector:
      matchExpressions:
        - key: sigaint.au/cluster-id
          operator: In
          values:
            - k3s-lhm-prod
            - k3s-lhm-devel
    kustomize:
      dir: base

  - name: exclude-others
    clusterSelector: {}
    doNotDeploy: true
