# fleet.yaml

targetRestrictions:
  - clusterSelector:
      matchExpressions:
        - key:  sigaint.au/cluster-id
          operator: NotIn
          values:
            - rancher-syd-prod

targetCustomizations:
  - name: k3s-lhm-prod
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: k3s-lhm-prod
    kustomize:
      dir: overlays/clusters/k3s-lhm-prod
  - name: k3s-lhm-devel
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: k3s-lhm-devel
    kustomize:
      dir: overlays/clusters/k3s-lhm-devel

  - name: rancher-syd-prod
    clusterSelector:
      matchLabels:
        sigaint.au/cluster-id: rancher-syd-prod

dependsOn:
  - selector:
      matchLabels:
        component: metallb-operator-install
