apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
spec:
  # conf/work for the single hostNetwork instance.
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
