apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
spec:
  # Single AdGuard writer; Recreate Deployment strategy when rescheduling.
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
