apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-ldap-bind
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: forgejo-ldap-bind
    creationPolicy: Owner
  data:
    - secretKey: bind-password
      remoteRef:
        key: LDAP_BIND_PASSWORD
    - secretKey: ca.crt
      remoteRef:
        key: LDAP_BIND_CA_CERT

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: forgejo-admin-external
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: FORGEJO_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: FORGEJO_ADMIN_PASSWORD
    - secretKey: email
      remoteRef:
        key: FORGEJO_ADMIN_EMAIL

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-mailer
  namespace: forgejo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: forgejo-mailer-config
    creationPolicy: Owner
  data:
    - secretKey: mailer
      remoteRef:
        key: FORGEJO_MAILER_CONFIG