---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-b2-velero-credentials
  namespace: velero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: b2-velero-credentials
  data:
    - secretKey: credentials-velero
      remoteRef:
        key: VELERO_B2_CREDENTIALS