# fleet.yaml
defaultNamespace: external-secrets
labels:
  component: external-secrets-operato-install
helm:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 0.9.13
  releaseName: external-secrets
  values:
    installCRDs: true
