# fleet.yaml
defaultNamespace: external-secrets
helm:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 0.9.13
  releaseName: external-secrets
  values:
    installCRDs: true

targetCustomizations:
  - name: rancher-syd-prod
    clusterSelector:
      matchLabels:
        cluster-id: rancher-syd-prod
    kustomize:
      dir: overlays/production