# traefik-values.yaml
service:
  enabled: true
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies: ["IPv4", "IPv6"]
providers:
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
